## Array: 
**An array is defined as a collection of items that are sorted at contigues memory location. It is container which can hold a fixed number of item and these items should be of the same data types.**

## What is NumPy?
- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy stands for Numerical Python.

In [1]:
import numpy as np # import numpy library as np

## Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

**NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.**


- 
The array object in NumPy is called
ndarray,-  
it provides a lot of supporting functios 
that make working with ndarray very es- y.

Arrays are very frequently used indata 
sc- ience,
where speed and resources ae very 
im
## Why is NumPy Faster Than Lists?
- 
NumPy arrays are stored at one continuous
place in memory unlike lists, s 
processs 
can access and manipulate tem 
very efficien- ly.

This behavior is called localty of 
reerence 
in computer - cience.

This is the main reason wh NumPy s 
faster 
than lists. Also it is ptimied to 
work 
with latest CPU architectures.
__________

**Advantages**
- Numpy library use much less memory to store data
- Numpy make it extremly easy to perform a mathematical operation on it
- Used for the creation of n-dimension array
- Finding element in numpy array is easy

In [2]:
l1 = [2,3,4]
l2 = [4,5,6]
print(l1+l2) # It does not perform actual mathematical operation on list, instead it concatenate list

[2, 3, 4, 4, 5, 6]


In [3]:
# For numpy case
l1 = np.array(l1)
l2 = np.array(l2)
print(l1+l2) # It perform actual mathematiocal operation on it

[ 6  8 10]


In [4]:
# In case of n-dimension array
l1 = np.array(range(1,100), ndmin=6)

In [5]:
l1.shape

(1, 1, 1, 1, 1, 99)

In [6]:
l1.ndim

6

# Array vs List:
- A list cannot handle mathematical operation direcctly
- An array consumes less memory than a list
- Using an array is faster than a list
- A list can store multiple data types while an array cannot
- A list is easy to modify since it store each elements individually
- In nested a list can store data of different size while in array you cannot store

In [7]:
arr = np.array(range(1,10))

## Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0,meaning that the first element has index 0, and the second has index 1 etc.

In [8]:
arr[0:3]

array([1, 2, 3])

In [9]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [10]:
type(arr)

numpy.ndarray

**2D Array**

In [11]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [8,9,54,34]
])

In [12]:
arr[0,0]

1

In [13]:
arr[0,]

array([1, 2, 3, 4])

In [14]:
arr[0,3]

4

In [15]:
arr[1:,1:] # print  6,7,8 / 9 54 34

array([[ 6,  7,  8],
       [ 9, 54, 34]])

In 2D array we need to provide both position of column and row

In [16]:
# Check shape of the array
arr.shape

(3, 4)

In [17]:
arr.size

12

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr.ndim

2

## Higher Dimensional Arrays
An array can have any number of
dimensions.

When the array is created, you an 
define the number of dimensons 
by using the ndmin argument.

## Example
Create an array with 5 dimensions and verify that it has 5 dimensions:

In [20]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Inspecting an Array

Functions:
- a.shape - Array dimension
- len(a) - Length of an array
- b.ndim - Give information about dimensions of array
- e.size - Number of array element
- b.dtype give information about datatype of array
- a.astype(int) - Convert an array into another datatype

In [21]:
a = np.array([[1,2,3],[3.4,5,'5']])

In [22]:
a.shape # Check shape of array, rows and columns

(2, 3)

In [23]:
len(a) # Total rows in array

2

In [24]:
a.ndim # Dimension of array

2

In [25]:
a.size # Total elements in array

6

In [26]:
a.dtype # Data type of elements, in array

dtype('<U32')

In [27]:
type(a) # Type of variable

numpy.ndarray

In [28]:
a.astype(float) # Change data type from one into another

array([[1. , 2. , 3. ],
       [3.4, 5. , 5. ]])

## Mathematical Operations and Functions on Array

In [29]:
arr1 = np.array([[1,2,3],[5,6,7]])
arr2 = np.array([[5,6,7],[75,34,22]])

In [30]:
arr1+arr2 # Add Two Elements in array

array([[ 6,  8, 10],
       [80, 40, 29]])

In [31]:
arr1-arr2 # Subtract two array

array([[ -4,  -4,  -4],
       [-70, -28, -15]])

In [32]:
arr1 * 5 # Multiply each element of arr1 with 5

array([[ 5, 10, 15],
       [25, 30, 35]])

In [33]:
np.add(arr1,arr2)

array([[ 6,  8, 10],
       [80, 40, 29]])

In [34]:
np.multiply(arr1, arr2)

array([[  5,  12,  21],
       [375, 204, 154]])

In [35]:
np.subtract(arr1,arr2)

array([[ -4,  -4,  -4],
       [-70, -28, -15]])

In [36]:
np.power(arr1,arr2)

array([[         1,         64,       2187],
       [1178063325,          0, 1344430353]])

In [37]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131]])

## Combining and Splitting Array

In [38]:
arr1 = np.array([1,2,34])
arr2 = np.array([6,4,6])

In [39]:
np.concatenate((arr1,arr2),axis=0)

array([ 1,  2, 34,  6,  4,  6])

In [40]:
arr1 = np.array([[1,2,3],[3,4,5]])
arr2 = np.array([[81,72,63],[53,44,52]])

In [41]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3, 81, 72, 63],
       [ 3,  4,  5, 53, 44, 52]])

In [42]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [81, 72, 63],
       [53, 44, 52]])

In [43]:
## Vertical Concatenation
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [81, 72, 63],
       [53, 44, 52]])

In [44]:
## Horizantal Concatination
np.hstack((arr1,arr2))

array([[ 1,  2,  3, 81, 72, 63],
       [ 3,  4,  5, 53, 44, 52]])

In [45]:
# For Spliting
a = np.array([1,2,3,4])

In [46]:
np.split(a, 2)

[array([1, 2]), array([3, 4])]

In [47]:
a = np.array(range(20))

In [48]:
b = np.split(a, 5)

In [49]:
b[2]

array([ 8,  9, 10, 11])

In [50]:
b[1]

array([4, 5, 6, 7])

In [51]:
b[0]

array([0, 1, 2, 3])

In [52]:
b[3]

array([12, 13, 14, 15])

In [53]:
b[4]

array([16, 17, 18, 19])

### 2D array

In [54]:
a = np.array([[1,2,3,4],[3,4,5,4],[7,8,9,8],[6,7,8,4]])

In [55]:
np.vsplit(a,2)

[array([[1, 2, 3, 4],
        [3, 4, 5, 4]]),
 array([[7, 8, 9, 8],
        [6, 7, 8, 4]])]

In [56]:
np.hsplit(a,2)

[array([[1, 2],
        [3, 4],
        [7, 8],
        [6, 7]]),
 array([[3, 4],
        [5, 4],
        [9, 8],
        [8, 4]])]

## Adding and Removing Element in Array

- np.append(h,g) # Append item to an array
- np.insert(a,1,5) # Insert new item to an array
- np.delete(a, [1]) # Delete item from an array

## Shape of an Array
- The shape of an array is the 
number of elements in each dimension.
- Get the Shape of an Array
NumPy arrays have an attribute 
called shape that returns a tuple 
with each index having the number 
of corresponding elements.

In [57]:
a.shape

(4, 4)

In [58]:
b = np.array([3,4,5])

In [59]:
c = np.append(a,b) # Append convert array from 2D to 1D and then append at the end of array

In [60]:
c

array([1, 2, 3, 4, 3, 4, 5, 4, 7, 8, 9, 8, 6, 7, 8, 4, 3, 4, 5])

In [61]:
c.shape

(19,)

In [62]:
np.insert(a,1,[5,6,7,8]) # first parameter is array name. 2nd is index, and third is value
# It also convert 2D into 1D if we dont pass index

array([1, 5, 6, 7, 8, 2, 3, 4, 3, 4, 5, 4, 7, 8, 9, 8, 6, 7, 8, 4])

In [63]:
a.shape

(4, 4)

In [64]:
np.insert(a,1,[4,5,6,7],axis=1)

array([[1, 4, 2, 3, 4],
       [3, 5, 4, 5, 4],
       [7, 6, 8, 9, 8],
       [6, 7, 7, 8, 4]])

In [65]:
np.insert(a,1,[4,5,6,7], axis=0)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [3, 4, 5, 4],
       [7, 8, 9, 8],
       [6, 7, 8, 4]])

In [66]:
np.delete(a,1)

array([1, 3, 4, 3, 4, 5, 4, 7, 8, 9, 8, 6, 7, 8, 4])

In [67]:
np.delete(a,1,axis=0)

array([[1, 2, 3, 4],
       [7, 8, 9, 8],
       [6, 7, 8, 4]])

In [68]:
a

array([[1, 2, 3, 4],
       [3, 4, 5, 4],
       [7, 8, 9, 8],
       [6, 7, 8, 4]])

In [69]:
b = np.delete(a,1,axis=1)

In [70]:
b

array([[1, 3, 4],
       [3, 5, 4],
       [7, 9, 8],
       [6, 8, 4]])

In [71]:
a

array([[1, 2, 3, 4],
       [3, 4, 5, 4],
       [7, 8, 9, 8],
       [6, 7, 8, 4]])

## Search, Sort and Filter

In [72]:
arr = np.array([13,45,65,3,12,2,0,23])

In [73]:
np.sort(arr)

array([ 0,  2,  3, 12, 13, 23, 45, 65])

In [74]:
np.sort(arr)[::-1]

array([65, 45, 23, 13, 12,  3,  2,  0])

In [75]:
# Same Rule apply for 2D
arr = np.array([[1,2,5,6,3,5],[8,64,43,2,1,9]])

In [76]:
np.sort(arr)

array([[ 1,  2,  3,  5,  5,  6],
       [ 1,  2,  8,  9, 43, 64]])

In [77]:
np.sort(arr,axis=0)

array([[ 1,  2,  5,  2,  1,  5],
       [ 8, 64, 43,  6,  3,  9]])

In [78]:
np.sort(arr,axis=1)

array([[ 1,  2,  3,  5,  5,  6],
       [ 1,  2,  8,  9, 43, 64]])

In [79]:
np.sort(arr)[::-1]

array([[ 1,  2,  8,  9, 43, 64],
       [ 1,  2,  3,  5,  5,  6]])

In [80]:
np.where(arr==5)

(array([0, 0], dtype=int64), array([2, 5], dtype=int64))

In [81]:
np.where(arr%2==0)

(array([0, 0, 1, 1, 1], dtype=int64), array([1, 3, 0, 1, 3], dtype=int64))

##### Same as SQL, in numpy we use where to search, find index

## Aggregating Function in Numpy 

In [82]:
a = np.array([3,4,5,6])

In [83]:
np.sum(a)

18

In [84]:
np.min(a)

3

In [85]:
np.max(a)

6

In [86]:
np.size(a)

4

In [87]:
np.mean(a)

4.5

In [88]:
np.median(a)

4.5

In [89]:
s = np.cumsum(a) # It add current value with all previous

'''
For Example
[20 30 40 50]
20 is first value so it comes as it is :20
30 is second value and previous is 20 so 30+20 = 50
40 is 3rd and previous is 30 and previous is 20 so 40+30+20 = 70
50 + 40 + 30 + 20 = 140 so cumsum is
20 50 70 140

'''
print(s)

[ 3  7 12 18]


In [90]:
a = np.array([20,30,40,50])
np.cumsum(a)

array([ 20,  50,  90, 140])

In [91]:
np.cumproduct(a)

array([     20,     600,   24000, 1200000])

In [92]:
np.cumprod(a)

array([     20,     600,   24000, 1200000])

In [93]:
a = [100, 150 ,190, 200, 250, 130]
b = [10, 50, 30, 40, 30, 10]
price = np.array(a)
quantity = np.array(b)

print(price, quantity)
total_sum = np.multiply(price, quantity)

print(total_sum)
print(f'Total Sum is {sum(total_sum)}')

[100 150 190 200 250 130] [10 50 30 40 30 10]
[1000 7500 5700 8000 7500 1300]
Total Sum is 31000


In [94]:
np.corrcoef([b,a])

array([[1.        , 0.48514675],
       [0.48514675, 1.        ]])

## NumPy Data Types

### Data Types in Python

By default, Python has the following data types:

- **Strings**: Used to represent text data. The text is given under quote marks.  
  Example: `"ABCD"`
  
- **Integer**: Used to represent integer numbers.  
  Example: `-1, -2, -3`
  
- **Float**: Used to represent real numbers.  
  Example: `1.2, 42.42`
  
- **Boolean**: Used to represent `True` or `False`.
  
- **Complex**: Used to represent complex numbers.  
  Example: `1.0 + 2.0j, 1.5 + 2.5j`

### Data Types in NumPy

NumPy offers additional data types and refers to them with a single character. Below is a list of all data types in NumPy and their respective characters:

- **i** - Integer
- **b** - Boolean
- **u** - Unsigned Integer
- **f** - Float
- **c** - Complex Float
- **m** - Timedelta
- **M** - Datetime
- **O** - Object
- **S** - String
- **U** - Unicode String
- **V** - Fixed Chunk of Memory for Other Types (Void)
k of memory for other type ( void )


In [95]:
# Integer
number = -1
print(type(number))  # Output: <class 'int'>


<class 'int'>


In [96]:
# Float
real_number = 1.2
print(type(real_number))  # Output: <class 'float'>

<class 'float'>


In [97]:
# Boolean
flag = True
print(type(flag))  # Output: <class 'bool'>

<class 'bool'>


In [98]:
# Complex
complex_number = 1.0 + 2.0j
print(type(complex_number))  # Output: <class 'complex'>

<class 'complex'>


### Data Type In Numpy

In [99]:
# i- integer
integer_array = np.array([1, 2, 3], dtype=np.int32)
print(integer_array.dtype)  # Output: int32

int32


In [100]:
# b- bool
boolean_array = np.array([True, False, True], dtype=np.bool_)
print(boolean_array.dtype)  # Output: bool

bool


In [101]:
# u- unsigned integer
unsigned_integer_array = np.array([1, 2, 3], dtype=np.uint8)
print(unsigned_integer_array.dtype)  # Output: uint8

uint8


In [102]:
# f- Float
float_array = np.array([1.1, 2.2, 3.3], dtype=np.float32)
print(float_array.dtype)  # Output: float32

float32


In [103]:
# c- Complex Float
complex_float_array = np.array([1+2j, 3+4j], dtype=np.complex64)
print(complex_float_array.dtype)  # Output: complex64

complex64


In [104]:
# m- timeDelta
timedelta_array = np.array([np.timedelta64(1, 'D'), np.timedelta64(2, 'D')], dtype='m')
print(timedelta_array.dtype)  # Output: timedelta64[D]

timedelta64[D]


In [105]:
# M- DateTime
datetime_array = np.array([np.datetime64('2024-01-01'), np.datetime64('2024-01-02')], dtype='M')
print(datetime_array.dtype)  # Output: datetime64[D]

datetime64[D]


In [106]:
# O- Object
object_array = np.array([1, "text", 3.0], dtype=np.object_)
print(object_array.dtype)  # Output: object

object


In [107]:
# S- String
string_array = np.array([b'abc', b'def'], dtype='S')
print(string_array.dtype)  # Output: |S3

|S3


In [108]:
# U- Unicode String
unicode_array = np.array(['abc', 'def'], dtype='U')
print(unicode_array.dtype)  # Output: <U3

<U3


## Checking the Data Type of an Array
The NumPy array object has a property 
called dtype that returns the data type 
of the array:


In [109]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)


int32


In [110]:
'''Example
Create an array with data type 4 bytes 
integer:
'''
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)


[1 2 3 4]
int32


In [111]:
'''Example
A non integer string like 'a' cannot 
be converted to integer 
(will raise an error):
'''
arr = np.array(['1', '2', '3'], dtype='i')
print(arr)
print(arr.dtype)

[1 2 3]
int32


In [112]:
'''Example
Change data type from float to 
integer by using 'i' as parameter value:
'''

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32
